"""paid status

Revision ID: 3f04ba117d12
Revises: d5cc943ae6fa
Create Date: 2024-01-25 16:12:04.766934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f04ba117d12'
down_revision = 'd5cc943ae6fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sherehe', schema=None) as batch_op:
        batch_op.alter_column('paid',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sherehe', schema=None) as batch_op:
        batch_op.alter_column('paid',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
